# Test description:
#   Run ddsenabler_test_app service_client against an AddTwoInts server.
#   Domain 33 is used.

services:
  ddsenabler:
    image: ${DDSENABLER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsenabler
    networks:
      - std_net
    volumes:
      - ../../../scripts:/scripts
    command: ./build/ddsenabler_test_app/test_app service_discovery

  add_two_ints_server:
    image: ${DDSENABLER_COMPOSE_TEST_ROS2_DOCKER_IMAGE}
    container_name: add_two_ints_server
    depends_on:
      - ddsenabler
    networks:
      - std_net
    environment:
      - ROS_DOMAIN_ID=33
    volumes:
      - ./../run_service_server_timeout.sh:/run_service_server_timeout.sh:ro
    entrypoint: ["/bin/bash", "/run_service_server_timeout.sh"]

networks:
  std_net:
  default:
    driver: none