# Test description:
#   Run ddsenabler_test_app action_server and a Fibonacci client sending goals.
#   Domain 33 is used by all containers.

services:
  ddsenabler:
    image: ${DDSENABLER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsenabler
    networks:
      - std_net
    command: ./build/ddsenabler_test_app/test_app action_server

  fibonacci_client_1:
    image: ${DDSENABLER_COMPOSE_TEST_ROS2_DOCKER_IMAGE}
    container_name: fibonacci_client_1
    depends_on:
      - ddsenabler
    networks:
      - std_net
    environment:
      - ROS_DOMAIN_ID=33
    command: ros2 run action_tutorials_cpp fibonacci_action_client

  fibonacci_client_2:
    image: ${DDSENABLER_COMPOSE_TEST_ROS2_DOCKER_IMAGE}
    container_name: fibonacci_client_2
    depends_on:
      - ddsenabler
    networks:
      - std_net
    environment:
      - ROS_DOMAIN_ID=33
    command: ros2 run action_tutorials_cpp fibonacci_action_client

  fibonacci_client_3:
    image: ${DDSENABLER_COMPOSE_TEST_ROS2_DOCKER_IMAGE}
    container_name: fibonacci_client_3
    depends_on:
      - ddsenabler
    networks:
      - std_net
    environment:
      - ROS_DOMAIN_ID=33
    command: ros2 run action_tutorials_cpp fibonacci_action_client

networks:
  std_net:
  default:
    driver: none